### ISSUE TITLE
Client disconnections: having a way to get back into the game

### ISSUE THREAD

**Issue by darthwalsh** [darthwalsh/Austerity#4]

**Comment by darthwalsh** [comment]
Server crashed after disconnect -> reconnect?

```
/storage/emulated/0/Download/Austerity/server/connection.js:16
      choice: /** @param {string} data */ data => this.onChoice(data),
                                                       ^

TypeError: this.onChoice is not a function
    at choice (/storage/emulated/0/Download/Austerity/server/connection.js:16:56)
    at WebSocket.<anonymous> (/storage/emulated/0/Download/Austerity/server/connection.js:35:7)
    at WebSocket.onMessage (/storage/emulated/0/Download/Austerity/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (events.js:327:22)
    at Receiver.receiverOnMessage (/storage/emulated/0/Download/Austerity/node_modules/ws/lib/websocket.js:1017:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/storage/emulated/0/Download/Austerity/node_modules/ws/lib/receiver.js:522:14)
    at Receiver.getData (/storage/emulated/0/Download/Austerity/node_modules/ws/lib/receiver.js:440:17)
    at Receiver.startLoop (/storage/emulated/0/Download/Austerity/node_modules/ws/lib/receiver.js:148:22)
    at Receiver._write (/storage/emulated/0/Download/Austerity/node_modules/ws/lib/receiver.js:83:10)
```

**Comment by darthwalsh** [comment]
After client disconnects, it takes a while for the server to see the disconnect...
